// Auto-generated from master_agreement_v30.html — tooltip dictionary (Thai)
// Hover-help shown on '?' icons next to field labels across MA / CA / TX modules.

export const TOOLTIPS: Record<string, string> = {
  // ─── Tab labels (Transaction Detail) ──────────────────────────────
  "TAB_FEE": "ค่าธรรมเนียมที่เกี่ยวข้องกับธุรกรรม — Fee Rate, Fee Cycle, ค่าธรรมเนียมราย period และวิธี recognize (Prepaid / Expense)",
  "TAB_ACCOUNTING": "ผูก GL Accounts ที่ใช้ post Journal Entry — กำหนด Account Type → GL Code · ค่าที่นี่จะถูกใช้สร้าง JE ทั้ง upfront และรายงวด",
  "TAB_SCHEDULE_CALCULATE": "ตารางการรับรู้รายงวด — Daily-prorated Fee/Interest พร้อม Post JE ราย period · Period 0 = ชำระ upfront, Period 1..N = รับรู้ค่าใช้จ่ายรายเดือน",
  "TAB_BALANCE_SUMMARY": "สรุปยอดคงเหลือปัจจุบัน — Outstanding, Prepaid Balance, Accrued, Fee paid/unpaid",
  "TAB_ROLL_OVER_HISTORY": "ประวัติการ Roll Over — แสดงโซ่ของเอกสารที่อ้างอิงต่อกัน (เช่น LG-001 → LG-002 → LG-003) ตามลำดับเวลา",
  "TAB_DOCUMENT": "เอกสารแนบ — รวมเอกสาร Master Agreement และ Credit Agreement (read-only) + เอกสารของธุรกรรมนี้ที่ upload เพิ่มได้",
  "TAB_PRIMARY_INFO": "ข้อมูลหลักของธุรกรรม — Bank Reference, CA, Amount, วันที่สำคัญ, สถานะ",
  "TAB_PRINCIPAL_AND_INTEREST": "ข้อมูลเงินต้น/ดอกเบี้ย — Rate Cards, Interest Cycle, Repayment Cycle",
  "TAB_INTEREST_RATE": "อัตราดอกเบี้ยที่ใช้กับธุรกรรม — รองรับ Fixed / MLR / MMR / MOR / MRR · มี Spread (+/-) คำนวณ Effective Rate อัตโนมัติ",
  "TAB_CHASSIS": "รายการรถ (Chassis) ที่อยู่ใต้ธุรกรรมนี้ — Floor Plan / P/N จะ lookup จาก inventory ของ NetSuite · แต่ละ chassis มี Cost + VAT แยก",

  // ─── Column / Row labels inside tabs (deduped — keep ONLY new keys) ──
  "JE": "ปุ่ม Post Journal Entry รายงวด — กดเพื่อสร้าง JE ลง GL · หลังโพสต์จะ lock ปุ่ม (จนกว่าจะ Reverse)",
  "FEE RATE (ANNUAL)": "อัตราค่าธรรมเนียมต่อปี — Effective Rate หลังคิด Spread จาก Rate Cards",
  "TOTAL FEE (SCHEDULED)": "ค่าธรรมเนียมรวมตาม schedule (ก่อนจ่ายจริง) — = Daily Rate × อายุสัญญารวม",
  "TOTAL FEE (PAID)": "ค่าธรรมเนียมที่จ่ายจริงแล้ว — รวมยอดที่ติ๊ก Paid ใน tab Fee",
  "TOTAL FEE (OUTSTANDING)": "ค่าธรรมเนียมที่ยังค้างจ่าย — = Scheduled − Paid",
  "AMORTIZE SCHEDULE": "ตารางตัดบัญชี Prepaid Expense รายเดือน — Daily-prorated × Days in Period",
  "ROLLOVER PARENT": "ตั๋ว/สัญญาเดิมที่ Roll Over มาจาก — null = ใบต้นทาง (ยังไม่เคย Roll Over)",
  "ROLLOVER COUNT": "จำนวนครั้งที่ Roll Over สะสมในโซ่ — ตรวจกับ MAXIMUM ROLL OVER (TIMES) ใน CA",
  "TRANSACTION DOCUMENTS": "เอกสารที่ผูกกับธุรกรรมนี้โดยตรง — upload ได้ที่นี่ · MA/CA docs แสดง read-only ด้านบน",
  "FROM MASTER AGREEMENT": "เอกสารดึงมาจาก Master Agreement ที่ CA นี้อ้างถึง — แก้ไขที่หน้า MA เท่านั้น",
  "FROM CREDIT AGREEMENT": "เอกสารดึงมาจาก Credit Agreement ที่ TX นี้อ้างถึง — แก้ไขที่หน้า CA เท่านั้น",
  "DR.": "เดบิต (Debit) — บัญชีฝั่งซ้าย เพิ่มทรัพย์สิน/ค่าใช้จ่าย หรือ ลดหนี้สิน/รายได้",
  "CR.": "เครดิต (Credit) — บัญชีฝั่งขวา เพิ่มหนี้สิน/รายได้ หรือ ลดทรัพย์สิน/ค่าใช้จ่าย",
  "PAID": "ติ๊กว่าค่าธรรมเนียมงวดนี้ชำระเรียบร้อยแล้ว — มีผลต่อ Balance Summary (Outstanding/Paid)",
  "PAID DATE": "วันที่ชำระจริง — ใช้แสดงใน audit trail · ถ้าไม่ระบุจะถือว่ายังไม่จ่าย",
  "RATE %": "อัตราดอกเบี้ย/ค่าธรรมเนียม (%) สำหรับงวดนั้นๆ",
  "FACILITY": "ประเภทวงเงินที่ใช้ (P/N · L/G · B/G · Floor Plan · O/D · T/R · FX Forward · Loan) — อ้างถึง CA Sub-Limit",
  "ROLE": "บทบาทของแถวใน Roll Over Chain — Original = ใบต้นทาง, Roll Over = ใบที่ถูก renew, Current = ใบที่กำลังดูอยู่",
  "P/N เดิม": "ตั๋ว P/N ใบเดิมที่กำลังจะ Roll Over ไปเป็นใบใหม่",
  "FP NAME": "ชื่อภายในของ Floor Plan Usage (เช่น 'Floor Plan Usage #FP00001') — ใช้แสดงในรายการและ JE description · ต่างจาก Floor Plan Number",
  "MATURITY DATE เดิม": "วันครบกำหนดชำระของตั๋ว P/N ใบเดิม (ก่อน Roll Over)",
  "CHASSIS NO. *": "เลขตัวถังรถ — เลือกจาก NetSuite Inventory ผ่าน Lookup เท่านั้น (key ลบไม่ได้)",

  "INACTIVE": "ปิดสัญญานี้ไม่ให้แสดงในรายการที่ใช้งาน",
  "FINANCE INSTITUTION": "ธนาคาร/สถาบันการเงินที่ออกวงเงินให้",
  "STATUS": "สถานะของเรกคอร์ด — Master Agreement: Approved / Draft / Expired / Terminated · Promissory Note: Draft / Approved / Roll Over / Repaid / Cancelled",
  "AGREEMENT STATUS": "สถานะของสัญญาวงเงิน (Draft / Approved / Expired / Terminated)",
  "MASTER AGREEMENT NAME": "ชื่อสัญญาวงเงินหลักที่ทำกับธนาคาร",
  "MASTER AGREEMENT": "อ้างอิงไปยัง Master Agreement (สัญญาวงเงินหลัก)",
  "START DATE": "วันที่เริ่มต้นของสัญญา",
  "END DATE": "วันที่สิ้นสุดของสัญญา",
  "SUBSIDIARY": "บริษัทในเครือที่เป็นเจ้าของหรือใช้วงเงินนี้",
  "TOP CREDIT LINE": "วงเงินรวมที่ธนาคารอนุมัติให้กลุ่มบริษัท",
  "TOP UTILIZATION": "ยอดที่ใช้ไปแล้วรวมจากทุก Sub-allocation",
  "TOP REMAINING": "วงเงินคงเหลือที่ยังใช้ได้",
  "CREDIT LINE": "วงเงินสินเชื่อที่ได้รับอนุมัติ",
  "CREDIT LINE (FOREIGN)": "วงเงินสินเชื่อในสกุลเงินต่างประเทศ — ใช้กรณี Currency ≠ THB · ระบบจะคำนวณ Credit Line (THB) จาก Conversion Rate × Foreign Amount",
  "UTILIZATION": "ยอดที่ใช้ไปแล้ว",
  "REMAINING CREDIT LINE": "วงเงินคงเหลือที่ยังใช้ได้",
  "D/E RATIO": "อัตราส่วนหนี้สินต่อทุน (Debt to Equity) ที่ธนาคารกำหนด",
  "DSCR RATIO": "ความสามารถในการชำระหนี้ (Debt Service Coverage Ratio)",
  "OTHER REQUIREMENT": "เงื่อนไขอื่น ๆ ที่ระบุในสัญญา",
  "CONSENT/WAIVER": "การยินยอม/ผ่อนผันที่ได้รับจากธนาคาร",
  "CONSENT/WAVIER": "การยินยอม/ผ่อนผันที่ได้รับจากธนาคาร",
  "COLLATERAL TYPE": "ประเภทหลักประกัน (ที่ดิน / รถ / เงินฝาก / อื่น ๆ)",
  "DOCUMENT NO": "เลขที่เอกสารสิทธิ์ (โฉนด, น.ส.3 ก, น.ส.3 ฯลฯ)",
  "LOCATION": "ที่ตั้งของหลักประกัน",
  "VALUE": "มูลค่าของหลักประกัน",
  "APPRAISAL VALUE": "มูลค่าจากการประเมินราคา",
  "APPRAISAL DATE": "วันที่ประเมินราคา",
  "MORTGAGE LIMIT": "วงเงินจำนองที่จดทะเบียนกับกรมที่ดิน",
  "VEHICLE REG NO": "เลขทะเบียนรถ",
  "MODEL/YEAR": "รุ่น/ปีของรถ",
  "PLEDGE AMOUNT": "วงเงินที่นำมาจำนำเป็นหลักประกัน",
  "BANK": "ธนาคารที่ฝากเงิน",
  "ACCOUNT NO": "เลขที่บัญชีเงินฝาก",
  "ACCOUNT NAME": "ชื่อบัญชีเงินฝาก",
  "DEPOSIT AMOUNT": "ยอดเงินฝากที่ใช้ค้ำประกัน",
  "COLLATERAL DESCRIPTION": "รายละเอียดหลักประกันทางธุรกิจ",
  "REGISTRATION NO": "เลขทะเบียน พ.ร.บ.หลักประกันทางธุรกิจ",
  "REGISTERED LIMIT": "วงเงินที่จดทะเบียนหลักประกันทางธุรกิจ",
  "DESCRIPTION": "คำอธิบายหลักประกัน",
  "SECURED LIMIT": "วงเงินที่หลักประกันค้ำได้",
  "GUARANTOR TYPE": "ประเภทผู้ค้ำประกัน (บุคคล / นิติบุคคล)",
  "NAME": "ชื่อผู้ค้ำประกัน",
  "POSITION/COMPANY": "ตำแหน่ง (ถ้าเป็นบุคคล) — เว้นว่างได้กรณีนิติบุคคล",
  "AMOUNT": "วงเงินที่ผู้ค้ำประกันรับผิดชอบ",
  "EXPIRY DATE": "วันสิ้นสุดของการค้ำประกัน",
  "CREDIT AGREEMENT NAME": "ชื่อสัญญาวงเงินย่อยภายใต้ Master Agreement",
  "CONTRACT NUMBER": "เลขที่สัญญาที่ออกโดยธนาคาร",
  "LOAN PURPOSE": "วัตถุประสงค์ของการกู้ยืมตามที่ระบุในสัญญา",
  "FACILITY TYPE": "ประเภทวงเงิน — P/N, O/D, T/R, Floor Plan, LG/BG, FX Forward, Hire Purchase, Lease, LC (Letter of Credit), Loan, SBLC (Standby LC)",
  "CREDIT TYPE": "Revolving = หมุนเวียนใช้ซ้ำได้ / Non Revolving = ใช้ครั้งเดียว",
  "CURRENCY": "สกุลเงินของวงเงิน",
  "CONVERSION DATE": "วันที่แปลงสกุลเงิน (สำหรับวงเงินสกุลต่างประเทศ)",
  "CONVERSION RATE": "อัตราแลกเปลี่ยนที่ใช้แปลงสกุลเงิน",
  "FX RATE": "อัตราแลกเปลี่ยน THB ต่อ 1 หน่วยสกุลเงินต่างประเทศ — ใช้แปลง Credit Line (Foreign) เป็น THB",
  "FX RATE DATE": "วันที่ใช้ FX Rate — อ้างอิงประกาศของธนาคาร ณ วันทำสัญญา",
  "REFERENCE FX FORWARD": "อ้างอิงสัญญา FX Forward ที่ทำ Hedge ไว้",
  "REMARK": "หมายเหตุเพิ่มเติม",
  "ROLL OVER CONDITION MAXIMUM TERM (DAYS)": "ระยะเวลาสูงสุดที่รวม Roll Over ได้ (หน่วย: วัน)",
  "MAXIMUM ROLL OVER (TIMES)": "จำนวนครั้งสูงสุดที่ Roll Over ได้",
  "CURTAILMENT OPTION": "อนุญาตให้ชำระคืนเงินต้นบางส่วนก่อนครบกำหนด",
  "CLASS": "หมวดหมู่ของรายการ (NetSuite Class)",
  "RELATED PARTIES": "บุคคล/บริษัทที่เกี่ยวข้องกับรายการนี้",
  "CHASSIS": "เลขตัวถังรถ — สำหรับ T/R / Floor Plan ที่ใช้ซื้อรถ",
  "CASH / BANK ACCOUNT": "บัญชีเงินสด/ธนาคารที่ใช้รับ-จ่าย",
  "INTEREST ACCOUNT": "บัญชีดอกเบี้ยจ่าย (Interest Expense)",
  "NOTE PAYABLE ACCOUNT": "บัญชีเจ้าหนี้/เงินกู้ยืมระยะสั้น",
  "PAYABLE ACCOUNT": "บัญชีเจ้าหนี้",
  "ACCRUED INTEREST ACCOUNT": "บัญชีดอกเบี้ยค้างจ่าย (Accrued Interest Payable)",
  "INTEREST TYPE": "ประเภทอัตราดอกเบี้ย — MLR / MOR / MRR / Fixed",
  "INTEREST RATE CONDITION (%)": "ส่วนต่างจากอัตราอ้างอิง เช่น MLR -1.5%",
  "INTEREST RATE (%)": "อัตราดอกเบี้ยสุทธิหลังคำนวณส่วนต่างแล้ว",
  "OVERLIMIT / CLEAN OVERDRAW": "ดอกเบี้ยพิเศษกรณีเบิกเกินวงเงินหรือ Clean OD",
  "INTEREST START DATE": "วันที่เริ่มคิดดอกเบี้ย — ปกติตรงกับวัน Transaction Date",
  "INTEREST EXPENSE ACCOUNT": "บัญชี Interest Expense ที่จะ Dr. ตอนคิดดอกเบี้ย — สำหรับ O/D ใช้ 5512101 ดอกเบี้ยจ่าย-เงินเบิกเกินบัญชี",
  "DATE": "วันที่บันทึกบัญชีของรายการ",
  "TRANSACTION TYPE": "ประเภทรายการบัญชี — Drawdown (เบิกเงินกู้/ตั้งหนี้) · Accrued Interest (ตั้งดอกเบี้ยค้างจ่ายสิ้นเดือน) · Reversal (กลับรายการ Accrued ต้นเดือนถัดไป) · Interest Payment (จ่ายดอกเบี้ยจริง) · Curtailment (ทยอยคืนเงินต้น 10/15/20%) · Repayment (ปิดสัญญา/คืนหนี้) · Write-off (ตัดหนี้สูญ)",
  "POSTING PERIOD": "งวดบัญชีที่ผ่านรายการ — Drawdown/Accrued ลงงวดเดือนนั้น · Reversal ลงงวดเดือนถัดไป (เช่น Nov 2024)",
  "JOURNAL ENTRY": "รหัส JV ที่ระบบสร้างอัตโนมัติ — คลิกเพื่อดู GL Posting",
  "REVERSE ACCRUED": "เครื่องหมาย ✓ บอกว่ารายการนี้ถูกตั้งให้ Auto-Reverse ในวันที่ 1 ของเดือนถัดไป (ตามมาตรฐาน Accrual Accounting)",
  "PERIOD": "งวดที่ของตารางคำนวณดอกเบี้ย (Period 0 = baseline ตอนเบิกเงิน)",
  "DAY": "จำนวนวันในงวด",
  "INTEREST PAID": "ดอกเบี้ยที่ต้องชำระในงวดนี้ (คำนวณจากเงินต้น × อัตรา × วัน ÷ 365)",
  "INTEREST": "ดอกเบี้ยที่คำนวณได้ในงวด",
  "PRINCIPLE BALANCE": "ยอดเงินต้นคงเหลือ ณ สิ้นงวด",
  "INTEREST BALANCE": "ดอกเบี้ยค้างจ่ายสะสมที่ยังไม่ผ่านรายการ",
  "DUE DATE": "วันครบกำหนดชำระดอกเบี้ยของงวดนั้น (ปกติ = สิ้นเดือน หรือ Maturity Date งวดสุดท้าย)",
  "ACTUAL": "รายการจริงที่เกิดขึ้น (Principal / Interest)",
  "TOTAL": "ยอดรวมตามสัญญา",
  "REPAYMENT": "ยอดที่ชำระไปแล้ว",
  "REMAINING": "ยอดคงเหลือที่ยังต้องชำระ",
  "EFFECTIVE INTEREST RATE (%)": "อัตราดอกเบี้ยที่ใช้คำนวณจริง — ดึงจาก Interest Rate tab (Type + Condition) ของ P/N นี้",
  "TERM (DAYS)": "จำนวนวันของสัญญา — คำนวณจาก Maturity Date − Transaction Date ใน Primary Information",
  "ACCUMULATED ACCRUED INTEREST": "ดอกเบี้ยค้างจ่ายสะสมตั้งแต่เริ่มสัญญา",
  "CHASSIS NO.": "เลขตัวถังของรถ",
  "CAR MODEL": "รุ่น/โมเดลของรถ",
  "PAYMENT DATE": "วันที่ชำระคืนตามจริง",
  "TRANSACTION NUMBER": "รหัสรายการธุรกรรมที่ต้องการชำระคืน (P/N, T/R, FP, etc.)",
  "PAYMENT CATEGORY": "ประเภทรายการที่ชำระ — Principal / Interest / Fee / Penalty",
  "PREPAID": "ติ๊กถ้าจ่ายค่าธรรมเนียมล่วงหน้า — ระบบจะสร้าง JE เป็น Prepaid Expense (Dr. Prepaid Expenses) แทน Expense ปกติ",
  "VALUE DATE": "วันที่ผูกพันตามเอกสาร L/G, B/G (อาจต่างจาก Start Date)",
  "AMOUNT (THB)": "มูลค่าค้ำประกันเป็นบาท",
  "AMOUNT (FOREIGN)": "มูลค่าค้ำประกันเป็นสกุลเงินต่างประเทศ (กรณี Currency ≠ THB)",
  "NUMBER": "เลขที่อ้างอิงหนังสือค้ำประกัน L/G, B/G",
  "FEE RATE (%)": "อัตราค่าธรรมเนียม L/G, B/G ต่อปี",
  "INTEREST RATE CONDITION / FEE (%)": "ส่วนต่างของค่าธรรมเนียมจากอัตราอ้างอิง",
  "AMORTIZE START DATE": "วันที่เริ่มต้นตัดบัญชีในงวดนี้",
  "AMORTIZE END DATE": "วันที่สิ้นสุดตัดบัญชีในงวดนี้",
  "FEE AMOUNT": "จำนวนค่าธรรมเนียมที่ตัดบัญชีในงวด (Daily rate × Days)",
  "GUARANTEE AMOUNT": "มูลค่าค้ำประกันคงเหลือ ณ สิ้นงวด",
  "PAYMENT (TIMES)": "จำนวนครั้งที่จ่ายค่าธรรมเนียม",
  "PAYMENT CYCLE": "รอบการจ่ายค่าธรรมเนียมตามที่ธนาคารกำหนด — Monthly / Quarterly / Semi-Annual / Annual / One-Time",
  "NETTING AP": "หักกลบลบหนี้กับ AP Car — เปิดไว้ ระบบจะ apply AP Bill (เจ้าหนี้รถ) กับ Floor Plan loan อัตโนมัติเมื่อ Save",
  "NETTING AR": "หักกลบลบหนี้กับ AR Car — เปิดไว้ เมื่อขายรถ ระบบจะนำเงินรับจากลูกหนี้ไปคืนเงินต้น Floor Plan อัตโนมัติ (Curtailment)",
  "ORIGINAL LOCATION": "สถานที่จัดเก็บเริ่มต้น (Showroom/Stock yard) ตอนรับรถจาก Vendor",
  "CURRENT LOCATION": "สถานที่เก็บปัจจุบัน — เปลี่ยนเมื่อโอนรถระหว่างสาขา",
  "LOCATION LAST MODIFIED": "วันที่อัพเดต Current Location ครั้งล่าสุด",
  "INVOICE NO.": "เลขใบกำกับภาษีจาก Vendor (เช่น BMW Thailand)",
  "VENDOR NAME": "ชื่อผู้ขายรถ (Vendor) — เป็นเจ้าหนี้รถของ MGC",
  "INVENTORY AMOUNT": "ราคาทุนรถ (Cost) ก่อน VAT — บันทึกเข้าบัญชี Inventory Floor Plan",
  "AP AMOUNT": "ยอดเจ้าหนี้รถทั้งหมด (รวม VAT) ที่ MGC ต้องจ่ายให้ Vendor",
  "AR INVOICE NO.": "เลขใบกำกับภาษีขายให้ลูกค้า — สร้างเมื่อขายรถออกจาก Floor Plan",
  "CUSTOMER": "ชื่อลูกค้าผู้ซื้อรถ — ลูกหนี้รถของ MGC",
  "AR AMOUNT": "ยอดลูกหนี้ที่ลูกค้าต้องจ่าย — เมื่อรับเงินจะนำไปคืนเงินต้น Floor Plan (ถ้าเปิด NETTING AR)",
  "TYPE": "ประเภทรถ (New / Used + ปี) — ใช้จับคู่กับ Floor Plan transaction",
  "VENDOR": "ผู้ขายรถ (เช่น BMW, Honda, Toyota) — เป็นเงื่อนไขจับคู่กับ Floor Plan",
  "EFFECTIVE START DATE": "วันที่เริ่มใช้เงื่อนไข Curtailment นี้",
  "EFFECTIVE END DATE": "วันที่สิ้นสุด — หลังวันนี้ Curtailment จะ Inactive อัตโนมัติ",
  "1ST CURTAILMENT (DAYS)": "งวดที่ 1: นับจากวันเบิกใช้ Floor Plan ครบกี่วันต้องเริ่มคืนเงินต้น",
  "1ST CURTAILMENT (%)": "งวดที่ 1: ต้องคืนเงินต้น % เท่าไหร่ของยอดเบิกใช้",
  "2ND CURTAILMENT (DAYS)": "งวดที่ 2: ครบกี่วันต้องคืน",
  "2ND CURTAILMENT (%)": "งวดที่ 2: % เงินต้นที่ต้องคืน",
  "3RD CURTAILMENT (DAYS)": "งวดที่ 3: ครบกี่วันต้องคืน (ปกติ = Term ของ Floor Plan)",
  "3RD CURTAILMENT (%)": "งวดที่ 3: % เงินต้นสุดท้าย — รวมทุกงวดต้อง = 100%",
  "CURTAILMENT REFERENCE": "Curtailment master record ที่ระบบจับคู่อัตโนมัติจาก Vendor + Type ของ Floor Plan",
  "DUE CURTAILMENT": "% ของเงินต้นที่ต้องคืนในงวดนี้ — มาจาก Curtailment master",
  "CURTAILMENT": "จำนวนเงินต้นที่ต้องคืนในงวดนี้ (= Principal × DUE CURTAILMENT %)",
  "INTEREST RATE": "อัตราดอกเบี้ยที่ใช้คำนวณงวดนี้",
  "PRINCIPAL BALANCE": "ยอดเงินต้นคงเหลือหลังจาก Curtailment ของงวด",
  "OD TRANSACTION DATE": "วันที่เริ่มใช้วงเงิน O/D",
  "OD TRANSACTION NUMBER": "เลขที่อ้างอิงรายการ O/D — ระบบสร้างอัตโนมัติ (รูปแบบ: O/D YYYYMM-XXXXXX)",
  "ENDING BALANCE": "ยอดคงเหลือสิ้นวัน — ตัวเลขลบ () = O/D ใช้ไปจริง · ตัวเลขบวก = มีเงินคงเหลือ",
  "ACTUAL INTEREST AMOUNT": "ดอกเบี้ยจริงที่ต้องจ่ายสิ้นเดือน — รวมดอกเบี้ยทุกวันที่ติดลบ",
  "UTILIZATION END OF MONTH": "ยอด O/D คงเหลือวันสิ้นเดือน — ใช้ดูการใช้วงเงิน",
  "TOTAL ENDING BALANCE": "ยอดรวมท้ายเดือน = Ending Balance + Interest Expense (Outstanding)",
  "INTEREST EXPENSE (OUTSTANDING)": "ดอกเบี้ยรวมของเดือนที่ยังไม่จ่าย — ตั้งเป็น Accrued Interest สิ้นเดือน",
  "ACCOUNTING PERIOD": "งวดบัญชีที่จะลง JE Interest Expense",
  "SOURCE": "ที่มาของข้อมูล: Import = นำเข้าจาก Bank Statement · Manual = บันทึกด้วยมือ",
  "LAST MODIFIED": "วันที่และเวลาที่บันทึก/แก้ไขรายการล่าสุด",
  "ACCOUNT NUMBER": "เลขบัญชีธนาคารที่ดึงข้อมูลมา",
  "TXN CODE": "รหัสรายการของธนาคาร — FE = Financial Entry, ENET = Electronic Transfer ฯลฯ",
  "DEBIT": "จำนวนเงิน Debit ในรายการ Bank Statement (เงินออก)",
  "CREDIT": "จำนวนเงิน Credit ในรายการ Bank Statement (เงินเข้า)",
  "BALANCE": "ยอดคงเหลือหลังรายการ — ตัวเลขลบ = O/D ใช้ไปจริง",
  "FINANCIAL INSTITUTION": "ธนาคารที่นำเข้าข้อมูล Bank Statement — แต่ละธนาคารใช้ Template ของตัวเอง",
  "NOTIONAL AMOUNT (FOREIGN)": "จำนวนเงินสกุลต่างประเทศที่ผูกสัญญา Forward — เช่น USD 10,000,000",
  "FORWARD RATE": "อัตราแลกเปลี่ยนตามสัญญา Forward (locked) — ใช้แลกที่วัน Maturity",
  "SPOT RATE": "อัตราแลกเปลี่ยน ณ วันที่ทำสัญญา — ใช้เปรียบเทียบกับ Forward Rate",
  "REFERENCE T/R CONTRACT": "อ้างอิงสัญญา T/R (Trust Receipt) ที่ Forward นี้ใช้คุ้มครองความเสี่ยง",
  "FAIR VALUE": "มูลค่ายุติธรรมของ Forward Contract ณ สิ้นงวด — Notional × Spot Rate ปัจจุบัน",
  "UNREALIZED GAIN/LOSS": "กำไร/ขาดทุนที่ยังไม่เกิดขึ้นจริง = Fair Value − Forward Value (ตั้งสิ้นเดือน + Auto Reverse)",
  "CANCELLATION OR AMENDMENT FEE": "ค่าธรรมเนียมจากการยกเลิก/แก้ไขสัญญา หรือใช้ Forward Rate ไม่ครบตามสัญญา",
  "SPOT FEE": "ค่าธรรมเนียมการใช้ Spot Rate ในกรณีพิเศษ",
  "GL DATE": "วันที่ลง General Ledger ของรายการค่าธรรมเนียม",
  "FEE ACCOUNT": "บัญชีค่าธรรมเนียมธนาคาร — สำหรับ FX ใช้ 5511101",
  "UNREALIZED GAIN/LOSS ACCOUNT": "บัญชี Unrealized Gain/Loss — สำหรับ FX Forward ใช้ 7100022",
  "PAYEE": "ผู้รับเงิน — เช่น ธนาคาร, Vendor",
  "EXCHANGE RATE": "อัตราแลกเปลี่ยนที่ใช้แปลง USD → THB ในการชำระ — สำหรับ FX Forward ใช้ Forward Rate ตามสัญญา",
  "AVAILABLE BALANCE": "ยอดที่ใช้ได้จริง (= Balance − pending)",
  "DOC. NO.": "เลขที่เอกสารภายใน",
  "PAYMENT METHOD": "วิธีการชำระเงิน — Cheque / Bank Transfer / Online",
  "CHEQUE NO.": "เลขที่เช็ค (กรณีจ่ายด้วยเช็ค)",
  "APPLIED TO": "ยอดเงินที่จะ Apply ไปจ่ายให้ Bills ที่เลือก",
  "CREDITS APPLIED": "Credits ที่ใช้ในการจ่าย (เช่น Vendor Credit Memo)",
  "AMT. DUE": "ยอดที่ต้องจ่าย ณ ปัจจุบัน",
  "DISC. DATE": "วันสิ้นสุด Discount (ถ้าจ่ายก่อนวันนี้ได้ส่วนลด)",
  "DISC. AVAIL.": "ส่วนลดที่ได้รับถ้าจ่ายก่อน Disc. Date",
  "DISC. TAKEN": "ส่วนลดที่จะใช้จริงในการชำระครั้งนี้",
  "PAYMENT": "ยอดที่จะจ่ายต่อรายการ",
  "WHT TYPE": "ประเภทภาษีหัก ณ ที่จ่าย (Withholding Tax)",
  "WHT BASE": "ฐานภาษี — มูลค่าที่จะคำนวณ WHT",
  "WHT RATE (%)": "อัตรา WHT — เช่น 3% (Service), 1% (Goods)",
  "WHT AMOUNT": "จำนวน WHT = WHT Base × WHT Rate",
  "T/R NUMBER": "เลขที่ Trust Receipt — เลขที่ออกโดยธนาคารเมื่อทำสัญญา T/R",
  "REFERENCE CONTRACT": "อ้างอิงสัญญา T/R เดิม (กรณี Roll Over) — ใช้เชื่อมโยง T/R ใหม่กับเก่า",
  "FLOOR PLAN NUMBER": "เลขที่อ้างอิงสัญญาเบิกใช้ Floor Plan (FP0001, FP0002, ...)",
  "TERMINATE DATE": "วันที่ยกเลิกหนังสือค้ำประกันก่อนกำหนด",
  "REFUND AMOUNT (THB)": "จำนวนค่าธรรมเนียมที่ธนาคารคืนกลับมา (บาท)",
  "P/N NUMBER": "เลขที่ตั๋วสัญญาใช้เงินที่ออกโดยธนาคาร",
  "BANK REFERENCE": "เลขที่อ้างอิงจากธนาคาร — ใช้ได้ทุกประเภท facility (P/N number, LG number, TR number, FXF deal ref ฯลฯ) · กรอกหลังได้รับเอกสารจาก bank",
  // ===== Context-specific labels (override existing keys) =====
  "P/N NAME": "ชื่อภายในของตั๋วสัญญาใช้เงิน (เช่น PNWC002) — ตั้งใช้อ้างอิงในระบบ MGC · ต่างจาก Bank Reference",
  "GUARANTOR NAME": "ชื่อผู้ค้ำประกัน",
  "RATE (%)": "อัตราดอกเบี้ยที่ใช้คำนวณงวดนั้น (Effective Rate = Base + Margin)",
  "PRINCIPAL BAL.": "เงินต้นคงค้าง — P/N เป็น bullet loan เงินต้นคงที่ตลอดอายุสัญญา",
  "INTEREST BAL.": "ดอกเบี้ยคงเหลือที่ยังไม่ได้ชำระ — รวมกับเงินต้นจ่ายที่ Maturity",
  "COST (THB)": "ราคาทุนของรถจาก Inventory (FA Master)",
  "CREDIT AGREEMENT": "สัญญาวงเงินที่ P/N นี้เบิกใช้ภายใต้",
  "TRANSACTION DATE": "วันที่ทำธุรกรรม / วันเบิกเงินกู้",
  "MATURITY DATE": "วันครบกำหนดชำระคืนเงินต้น",
  "REFERENCE TRANSACTION": "รายการอ้างอิงที่เกี่ยวข้อง เช่น P/N รายการก่อนหน้า (กรณี Roll Over), FX Forward, T/R",
  "ID": "รหัสลำดับของ Master Interest Rate (ระบบสร้างอัตโนมัติ)",
  "DATE EFFECTIVE": "วันที่อัตราดอกเบี้ยมีผลบังคับใช้",
  "END EFFECTIVE DATE": "วันที่อัตรานี้สิ้นสุด (ถ้าว่าง = ยังใช้ได้ปัจจุบัน)",
  "LEASE ID": "รหัสภายในของสัญญาเช่า ระบบสร้างอัตโนมัติ (เช่น 202411150001311)",
  "LEASE NAME": "ชื่อสัญญาเช่าซื้อ ใช้อ้างอิงในรายงานและ Journal Entry (เช่น MCR_9233162)",
  "LEASE COMPANY NAME": "บริษัทผู้ให้เช่า/ Leasing Company ที่ออกสัญญา",
  "CONTRACT DATE": "วันที่ทำสัญญาเช่าซื้อ",
  "CONTRACT INTEREST RATE": "อัตราดอกเบี้ยตามสัญญา (Nominal rate) — แสดงเป็น % ต่อปี",
  "LEASE CLASSIFICATION": "ประเภทการบันทึกบัญชี — Financing (สัญญาเช่าทางการเงิน — รับรู้สินทรัพย์/หนี้สิน) · Operating (สัญญาเช่าดำเนินงาน — รับรู้เป็นค่าใช้จ่าย)",
  "PAYMENT FREQUENCY": "ความถี่การชำระค่างวด — Monthly / Quarterly / Yearly",
  "POSTING LEASE": "เปิดให้บันทึก JV จากสัญญานี้เข้าระบบบัญชี",
  "JV AUTO APPROVE": "ให้ระบบ Approve Journal Entry อัตโนมัติเมื่อสร้างจาก Process J03",
  "INSTALLMENT START DATE": "วันครบกำหนดงวดแรก (Due date งวด #1)",
  "INSTALLMENT END DATE": "วันครบกำหนดงวดสุดท้าย — คำนวณอัตโนมัติจาก Installment Start Date + Lease Term",
  "PAYMENT START DATE": "วันครบกำหนดงวดแรก (Due date งวด #1)",
  "PAY AT END OF MONTHS": "จ่ายค่างวดในวันสิ้นเดือน (End-of-month convention)",
  "LEASE TERM (MONTHS)": "จำนวนงวดทั้งหมด (เดือน) — Term ≤ 12 = ระยะสั้น · > 12 = ระยะยาว (MOM Day 4 ส่วน 3 §1.1)",
  "PAYMENT TYPE": "รูปแบบการชำระคืน — อิงตาม Loan: Fix Installment (ค่างวดเท่ากัน), Fix Principal (เงินต้นเท่ากัน), Balloon, Grace Period, ชำระต้นงวด/ปลายงวด",
  "AMOUNT PER MONTH": "ค่างวดต่อเดือน (รวมเงินต้น + ดอกเบี้ย ก่อน VAT)",
  "PRINCIPAL AMOUNT": "มูลหนี้เงินต้นทั้งหมดของสัญญา (ยังไม่รวมดอกเบี้ย/VAT) — สำหรับ HP จะเท่ากับ Net Vehicle Cost (Vehicle Price − Down Payment)",
  "BALLOON PAYMENT": "เงินก้อนสุดท้ายที่จ่ายเพิ่มจากงวดปกติ — ใช้เมื่อโครงสร้าง P/N มีงวด Balloon ตอนปิดสัญญา",
  "INCLUDE BALLOON PAYMENT IN INSTALLMENT": "ติ๊ก = รวม Balloon เข้างวดสุดท้าย (จ่ายพร้อมงวด 59) · ไม่ติ๊ก = แยกจ่าย Balloon เป็นงวดถัดไป (งวด 60)",
  "EFFECTIVE INTEREST RATE PER YEAR": "อัตราดอกเบี้ยที่แท้จริงต่อปี (Effective rate) — คำนวณจาก IRR ของ cash flow",
  "EFFECTIVE INTEREST RATE PER MONTH": "อัตราดอกเบี้ยที่แท้จริงต่อเดือน — ใช้ในตาราง Amortization (Read-only)",
  "CALCULATE INTEREST AT THE END": "คำนวณดอกเบี้ยที่ปลายงวด (End-of-period) แทนต้นงวด",
  "VAT": "รหัส VAT ที่ใช้กับค่างวดเช่าซื้อ — ค่าเริ่มต้น I-VATS-7%",
  "VEHICLE PRICE": "ราคารถทั้งคัน (ก่อนหักเงินดาวน์) — ดึงจาก NetSuite Inventory · ใช้เป็น base สำหรับคำนวณ Net Vehicle Cost (MOM Day 4 §9.2)",
  "DOWN PAYMENT": "เงินดาวน์ที่ลูกค้าจ่ายเองตอนซื้อรถ (ไม่อยู่ในตารางผ่อน) — Vehicle Price × % Down · ส่วนที่เหลือ (Net Vehicle Cost) จึงเข้าตารางผ่อน HP (MOM Day 4 §9.2)",
  "NET VEHICLE COST": "ยอดสินเชื่อ HP จริง = Vehicle Price − Down Payment · เป็น Principal Amount ตั้งต้นใน Schedule (auto-compute, read-only)",
  "ใช้สินเชื่อจากธนาคาร (USE BANK LOAN)": "ติ๊ก = สัญญาเช่าที่ใช้สินเชื่อจากธนาคาร (ต้องผูก MA/CA) · ไม่ติ๊ก = Pure IFRS 16 (MGC คำนวณ NPV ใน Excel · ข้ามขั้นตอน MA/CA · MOM §2.2)",
  "UPFRONT PAYMENT": "เงินจ่ายล่วงหน้า ณ Day 1 (Prepaid lump sum) — ไม่นำมาคิด NPV/Lease Liability แต่บวกเข้า ROU Asset · ผลคือ ROU > Lease Liability ตั้งแต่ Day 1 (MOM Day 4 บ่าย §2.1)",
  "GRACE PERIOD (MONTHS)": "จำนวนเดือนที่ไม่ต้องจ่ายค่าเช่าช่วงต้นสัญญา (Free period) — ไม่นำมาคิดดอกเบี้ย · ROU ยังคำนวณค่าเสื่อมตั้งแต่ Day 1 (MOM Day 4 บ่าย §3.1)",
  "PREPAID PERIODS": "จำนวนงวดสุดท้ายที่จ่ายล่วงหน้าตั้งแต่ Day 1 — ไม่นำมาคำนวณ NPV (ไม่ใช่ภาระอนาคต) แต่นำไปรวมในยอด ROU Asset (MOM Day 4 บ่าย §3.2)",
  "TERM (M)": "ระยะเวลาสัญญา (เดือน)",
  "AMOUNT/MONTH": "ค่างวดต่อเดือน",
  "CLASSIFICATION": "ประเภทการบันทึกบัญชี — Financing / Operating",
  "#": "ลำดับงวด — \"B\" = Balloon row",
  "PAYMENT DATE SCHEDULE": "วันครบกำหนดชำระตามตาราง",
  "INSTALLMENT": "ค่างวดที่ต้องจ่าย (เงินต้น + ดอกเบี้ย ก่อน VAT)",
  "INCLUDED ONE-TIME PAYMENT": "จำนวนเงินจาก One Time Payments tab ที่ตรงกับวันครบกำหนดงวดนี้ (เช่น Balloon Payment)",
  "TOTAL PAYMENT": "ยอดรวมที่จ่ายในงวด (Installment + Included One-Time Payment ถ้ามี)",
  "TOTAL PAYMENT (INC. VAT)": "ยอดรวมที่จ่ายในงวด รวม VAT",
  "PRINCIPAL": "ส่วนเงินต้นในงวดนั้น",
  "VAT 7%": "ภาษีมูลค่าเพิ่ม 7% บนค่างวด",
  "TOTAL PAID": "ยอดเงินที่จ่ายจริงในงวดนั้น (Installment + VAT + Balloon ถ้ามี)",
  "OUTSTANDING": "ยอดเงินต้นคงเหลือหลังจ่ายงวดนั้น",
  "DEFERRED INTEREST BALANCE": "ยอดดอกเบี้ยรอตัดบัญชีคงเหลือ — เริ่มต้น = TOTAL INTEREST · ลดลงทุกงวดตามดอกเบี้ยที่รับรู้",
  "VAT BALANCE": "ยอด VAT ค้างจ่ายคงเหลือ — เริ่มต้น = TOTAL VAT · ลดลงทุกงวด",
  "PRINCIPAL BALANCE (INC. VAT)": "ยอดเงินต้นคงเหลือ + VAT คงเหลือ",
  "TOTAL PAYMENT (INC VAT)": "รวมยอดที่ต้องจ่ายตลอดอายุสัญญา รวม VAT",
  "TOTAL PRINCIPAL": "รวมเงินต้นทั้งสัญญา",
  "TOTAL INTEREST": "รวมดอกเบี้ยตลอดอายุสัญญา",
  "TOTAL VAT": "รวม VAT ตลอดอายุสัญญา",
  "TOTAL RIGHT-OF-USE ASSETS (ROU)": "มูลค่าสินทรัพย์สิทธิการใช้ — เท่ากับ TOTAL PRINCIPAL ในสัญญาเช่าแบบ Financing",
  "REMAINING BALANCE": "ยอดคงเหลือหลังจ่ายงวดนั้น (Principal · Deferred Interest · VAT · Total)",
  "NOTE": "บันทึกเพิ่มเติม / เลขที่อ้างอิงเอกสารอื่น (HLT, RTV, PO ฯลฯ)",
  "FILE": "ไฟล์เอกสารแนบ (PDF / DOCX / JPG / PNG)",
  "SIZE": "ขนาดไฟล์",
  "UPLOADED": "วันที่อัปโหลดไฟล์",
  "ACTION": "การดำเนินการกับไฟล์ — Download / Delete",
  "ASSET NAME": "ชื่อสินทรัพย์ที่เช่า (เช่น Mercedes-Benz GLC 220d)",
  "ASSET NUMBER": "เลขที่สินทรัพย์ในระบบ Asset Master (เช่น RTV2400278) — ใช้อ้างอิงในรายงานและ Inventory",
  "ASSET DESCRIPTION": "รายละเอียดสินทรัพย์ที่เช่า (รุ่น · ยี่ห้อ · เลขรุ่น)",
  "COST": "มูลค่าทุนของสินทรัพย์ ณ วันรับโอน (รวม VAT ถ้าจดบัญชีแบบ inclusive)",
  "CHASSIS NO / SERIAL": "เลขตัวถัง (รถ) หรือ Serial Number (เครื่องจักร)",
  "MODEL / YEAR": "รุ่นและปีที่ผลิต",
  "ACQUISITION COST": "มูลค่าทุนของสินทรัพย์ ณ วันรับโอน — โดยปกติ = Principal Amount",
  "ACQUISITION DATE": "วันรับมอบสินทรัพย์ / วันเริ่มต้น ROU",
  "USEFUL LIFE (M)": "อายุการใช้งาน (เดือน) — ใช้คำนวณค่าเสื่อม ROU Asset",
  "EDIT": "แก้ไข Asset record (เปิด Asset Master form)",
  "REMOVE": "ปลดการผูก Asset ออกจากสัญญาเช่านี้ (Asset record ยังอยู่ใน Asset Master)",
  "VIEW": "มุมมองที่เลือกแสดง — Default View / Compact / By Cost / Customize",
  "ASSETS": "ตัวกรอง Asset list — All / Linked Only / Unlinked Only",
  "VERSION": "หมายเลขเวอร์ชันของสัญญา — v1.0 = Initial · v2.0+ = หลัง Modification/Remeasurement",
  "EFFECTIVE DATE": "วันที่เวอร์ชันนั้นมีผลบังคับใช้",
  "MODIFIED BY": "ผู้ทำการแก้ไข version นี้",
  "REASON": "เหตุผลการสร้าง version ใหม่ — Initial Creation / Term Extension / Rate Change / Remeasurement",
  "DATE FROM": "วันที่เริ่มต้นของช่วงที่ต้องการประมวลผล (รวมงวดที่ครบกำหนดในช่วงนี้)",
  "DATE TO": "วันสิ้นสุดของช่วงที่ต้องการประมวลผล",
  "MODIFICATION DATE": "วันที่มีผลการปรับปรุงสัญญา (Effective Date) — ระบบจะ Auto Cancel Journal และ AP Bill ที่ post หลังจากวันที่นี้",
  "SUBSIDIARIES": "บริษัทในเครือที่ต้องการรัน batch — เลือกได้หลายรายการ (Ctrl/Cmd + click)",
  "ACCOUNTING BOOK": "สมุดบัญชีที่จะบันทึก JV — Primary (มาตรฐานบัญชีหลัก) · GAAP / IFRS Adjustment (สำหรับปรับยอดมาตรฐานต่างประเทศ) · Tax Book",
  "LEASES PROCESSED": "จำนวนสัญญาเช่าที่ผ่านเงื่อนไขและถูกประมวลผล",
  "JV ENTRIES CREATED": "จำนวน Journal Entry ที่ระบบสร้าง = Leases × Periods × Books",
  "TOTAL AMOUNT (THB)": "ยอดเงินรวมของ JV ทั้งหมดที่สร้างในการรันครั้งนี้",
  "ERRORS / SKIPPED": "จำนวน JV ที่สร้างไม่สำเร็จ หรือถูกข้ามเพราะเงื่อนไขไม่ครบ",
  "JV ID": "เลขที่ Journal Entry ที่ระบบสร้าง — กดเพื่อเปิดดูรายละเอียด",
  "PERIOD #": "ลำดับงวดในรอบการประมวลผล (เริ่มจาก 1 ที่ Date From)",
  "PERIOD DATE": "วันครบกำหนดของงวดที่บันทึก",
  "BOOK": "Accounting Book ที่บันทึก JV นี้",
  "PERIOD OF PAYMENTS (MONTH)": "ระยะเวลาทยอยรับรู้ค่าใช้จ่าย (เดือน) — ใช้กับ Prepaid Lease / Initial Direct Cost เพื่อกระจายเป็นรายเดือน · ฟิลด์จะเปิดใช้งานเมื่อเลือก Type ที่เกี่ยวข้อง",
  "EXCLUDE FROM LIABILITY": "ติ๊ก = ไม่นำยอดนี้ไปลดหนี้สินสัญญาเช่า (Lease Liability) — ใช้กับค่าใช้จ่ายที่จ่ายให้บุคคลที่สาม เช่น ค่าประกัน",
  "FREQUENCY": "ความถี่จ่าย — Monthly / Quarterly / Yearly",
  "CREATED DATE": "วันที่สร้างเรกคอร์ด",
  "CREATED BY": "ผู้สร้างเรกคอร์ด",
  "LAST MODIFIED DATE": "วันที่แก้ไขล่าสุด",
  "LAST MODIFIED BY": "ผู้แก้ไขล่าสุด",
  "EXTERNAL ID": "รหัสจากระบบภายนอก (สำหรับการอ้างอิง integration)",
  "RECORD VERSION": "เวอร์ชันของเรกคอร์ด",
  "1 YEAR OR LESS": "ยอดที่ครบกำหนดภายใน 12 เดือนข้างหน้า (Current Portion)",
  "> 1 TO 5 YEARS": "ยอดที่ครบกำหนดในเดือนที่ 13-60 (Non-current Portion ภายใน 5 ปี)",
  "MORE THAN 5 YEARS": "ยอดที่ครบกำหนดเกิน 5 ปี (Long-term Non-current)",
  "DEFERRED INTEREST": "ดอกเบี้ยรอตัดบัญชี (ยังไม่รับรู้เป็นค่าใช้จ่าย)",
  "VIEW GL CLASSIFICATION": "เปิด Journal Voucher ที่บันทึกยอดเริ่มต้น (เช่น JV#004) เพื่อดู GL Account ที่ใช้",
  "USER": "ผู้ใช้ที่ดำเนินการ",
  "FIELD": "ฟิลด์ที่ถูกแก้ไข",
  "OLD VALUE": "ค่าเดิมก่อนแก้ไข",
  "NEW VALUE": "ค่าใหม่หลังแก้ไข",
  "EDIT | VIEW": "แก้ไขรายการ (Edit) หรือดูรายละเอียด (View) — กดเพื่อเปิดฟอร์มของรายการนั้น",
  "PARENT-CHILD (SUBSIDIARY)": "บริษัทย่อย/บริษัทในเครือที่อยู่ใต้สัญญานี้ — เลือกได้หลายบริษัท แต่ละบริษัทมีวงเงิน/ยอดใช้แยกกัน",
  "EFFECTIVE INTEREST RATE": "อัตราดอกเบี้ยที่แท้จริง (Effective Rate) ของสัญญา/วงเงินนี้",
  "POSITION": "ตำแหน่งของผู้ค้ำประกันในบริษัท เช่น กรรมการ / ผู้ถือหุ้น / กรรมการผู้จัดการ",
  "COMPANY": "ชื่อบริษัทที่ผู้ค้ำประกันเกี่ยวข้อง — ถ้าเป็นบุคคลธรรมดาให้เว้นว่าง",
  "AMOUNT (บาท)": "จำนวนเงินที่ค้ำประกัน (สกุลบาท) — Joint and Several = ทุกคนรับผิดเต็มจำนวน · Limited = แต่ละคนตามจำนวนระบุ",
  "TAX ID": "เลขประจำตัวผู้เสียภาษี (13 หลักสำหรับนิติบุคคล / 13 หลักสำหรับบุคคล)",
  "PHONE": "เบอร์โทรศัพท์สำหรับติดต่อ",
  "ADDRESS": "ที่อยู่สำหรับการติดต่อหรือการส่งเอกสาร",
  "PAYEE NAME": "ชื่อผู้รับเงิน — ใช้ในใบสำคัญจ่ายและการตรวจสอบ",
  "ACCOUNT": "รหัสบัญชี/ชื่อบัญชีใน Chart of Accounts (GL)",
  "ADDITIONAL NOTE": "หมายเหตุเพิ่มเติม / รายละเอียดที่ต้องการบันทึก",
  "LINK": "ลิงก์ไปยังเอกสาร/ระบบภายนอก หรือ Drive ที่เกี่ยวข้อง",
  "MONTH": "เดือนที่ครบกำหนดงวด Curtailment",
  "1ST CURTAILMENT": "อัตราหรือยอดของ Curtailment งวดที่ 1 (เช่น 5% ภายใน 90 วัน)",
  "2ND CURTAILMENT": "อัตราหรือยอดของ Curtailment งวดที่ 2 (เช่น 10% ภายใน 180 วัน)",
  "3RD CURTAILMENT": "อัตราหรือยอดของ Curtailment งวดที่ 3 (เช่น 15% ภายใน 270 วัน)",
  "%": "ร้อยละของยอดเดิมที่ต้องชำระลด (Curtailment percentage)",
  "TERM": "ระยะเวลา (เช่น จำนวนวันถึงครบกำหนด หรือ ระยะเวลาสัญญา)",
  "DAYS": "จำนวนวัน",
  "REF NO.": "เลขที่อ้างอิงของรายการ",
  "REFERENCE NO.": "เลขที่อ้างอิงเอกสาร เช่น เลขใบ PO, เลขใบเสร็จ",
  "DOCUMENT #": "เลขที่เอกสาร",
  "NOTIONAL AMOUNT": "มูลค่าเงินต้นอ้างอิง (Notional) ของสัญญา FX/Derivative",
  "ORIG. AMT.": "จำนวนเงินตั้งต้น (Original Amount) ก่อนการตัดชำระ",
  "ACTUAL INTEREST": "ดอกเบี้ยจริงที่เกิดขึ้น (คำนวณจากยอดและจำนวนวันจริง)",
  "FEE": "ค่าธรรมเนียม",
  "FEE RATE": "อัตราค่าธรรมเนียม (% ต่อปี หรือ % ต่อรายการ)",
  "MEMO": "บันทึก/ข้อความเพิ่มเติม",
  "DATE DUE": "วันครบกำหนดชำระ",
  "TIME": "เวลาที่ทำรายการ",
  "DR": "เดบิต (Debit) — บัญชีฝั่งซ้าย เพิ่มทรัพย์สิน/ค่าใช้จ่าย หรือ ลดหนี้สิน/รายได้",
  "CR": "เครดิต (Credit) — บัญชีฝั่งขวา เพิ่มหนี้สิน/รายได้ หรือ ลดทรัพย์สิน/ค่าใช้จ่าย",
  "FILE NAME": "ชื่อไฟล์ที่อัปโหลด",
  "UPLOADED BY": "ผู้อัปโหลดไฟล์",
  "UPLOADED DATE": "วันที่อัปโหลดไฟล์",
  "PAYMENT DATE FROM": "วันที่เริ่มต้นของช่วงวันที่ชำระ — ใช้กรองรายการที่ชำระตั้งแต่วันนี้",
  "PAYMENT DATE TO": "วันที่สิ้นสุดของช่วงวันที่ชำระ — ใช้กรองรายการที่ชำระถึงวันนี้",
  "JV – L/G, B/G-FEE": "รายการ Journal Entry สำหรับค่าธรรมเนียม L/G หรือ B/G",
  "ลำดับ": "ลำดับที่ของรายการ",
  "วันครบกำหนดชำระ": "วันที่ครบกำหนดชำระเงินตามสัญญา",
  "วันที่ครบกำหนดชำระ": "วันที่ครบกำหนดชำระเงินตามสัญญา",
  "ประเภทรายการ": "ประเภทของรายการ เช่น เงินต้น / ดอกเบี้ย / ค่าธรรมเนียม",
  "ประเภทสินเชื่อ": "ประเภทของวงเงินสินเชื่อ เช่น P/N · O/D · T/R · LG/BG · Floor Plan · FX Forward · Lease",
  "เงินต้นค้างชำระ": "ยอดเงินต้นที่ยังไม่ได้ชำระ",
  "ดอกเบี้ยค้างชำระ": "ยอดดอกเบี้ยที่ยังไม่ได้ชำระ",
  "ค่าธรรมเนียม / ค่าใช้จ่ายค้างชำระ": "ยอดค่าธรรมเนียมและค่าใช้จ่ายอื่นที่ยังไม่ได้ชำระ",
  "ยอดค้างชำระ": "ยอดที่ยังไม่ได้ชำระ",
  "ยอดรวมค้างชำระ": "ยอดรวมที่ยังไม่ได้ชำระทั้งหมด (เงินต้น + ดอกเบี้ย + ค่าธรรมเนียม)",
  "ดำเนินการ": "การดำเนินการที่ทำได้กับรายการ เช่น แก้ไข ดู ลบ",
  "วิธีการชำระ": "ช่องทางการชำระเงิน เช่น โอนผ่านธนาคาร / เช็ค / เงินสด / หักบัญชีอัตโนมัติ",
  "ธนาคาร": "ธนาคารที่ใช้ในการรับ/จ่ายเงิน",
  "เจ้าหน้าที่ธนาคาร": "เจ้าหน้าที่ดูแลของธนาคาร (Relationship Manager)",
  "ชื่อลูกหนี้": "ชื่อลูกหนี้/ผู้กู้ — บุคคลหรือบริษัทที่เป็นเจ้าของหนี้",
  "รหัสบัญชี": "รหัสบัญชีใน Chart of Accounts (GL Code)",
  "เลขที่สัญญา": "เลขที่สัญญาเงินกู้/สัญญาวงเงิน",
  "FP NAME / NUMBER": "ชื่อ Floor Plan + เลขสัญญา — ใช้อ้างอิงในระบบ",
  "CHASSIS COUNT": "จำนวนรถใน Floor Plan — นับจากตาราง Chassis",
  "B/G NUMBER": "เลขที่หนังสือค้ำประกัน (B/G Number) — เลขทะเบียนที่ธนาคารออกให้",
  "PRINCIPAL (THB)": "จำนวนเงินต้นของตั๋ว P/N ในสกุลบาท",
  "REFERENCE": "รายการอ้างอิง — ใช้ลิงก์ไปยังตั๋ว/สัญญาก่อนหน้า (เช่นกรณี Roll Over จะอ้างถึงตั๋วเดิม)",
  "ROLL OVER HISTORY": "ประวัติการ Roll Over ตั๋ว P/N — แสดงโซ่ของตั๋วที่อ้างอิงต่อกัน (PNWC001 → PNWC002 → PNWC003)",
  "ACCRUED INTEREST": "ดอกเบี้ยค้างจ่าย/ค้างรับที่บันทึกเป็นค่าใช้จ่าย/รายได้สิ้นเดือน — รายการนี้จะถูก Reverse อัตโนมัติในเดือนถัดไป",
  "ISSUE DATE": "วันที่ออกตั๋ว P/N ใบนี้",
  "DRAWDOWN": "การเบิกเงินจากธนาคารตามวงเงินที่ได้รับอนุมัติ — สร้างหนี้ใหม่",
  "REVERSAL": "กลับรายการ Accrued ในเดือนถัดไป (วันที่ 1) เพื่อหลีกเลี่ยงการนับซ้ำตอนจ่ายจริง — pattern มาตรฐานของ Accrual Accounting",
  "INTEREST PAYMENT": "ดอกเบี้ยจ่ายจริงตามรอบบิล",
  "WRITE-OFF": "ตัดหนี้สูญ — ใช้กรณีรถถูกขโมย/หาย หรือลูกค้าไม่ชำระตามกำหนด",
  "ACCOUNT TYPE": "ประเภทบัญชีในระบบ Account Mapping — เช่น Cash/Bank, Interest, Note Payable, Inventory, AP/AR Car, Fee Income/Expense, FX Gain/Loss",
  "GL ACCOUNT": "รหัสบัญชี GL ใน Chart of Accounts ที่ผูกกับ Account Type นี้ — ระบบจะใช้รหัสนี้เมื่อ post Journal Entry",
  "LOAN NUMBER": "เลขที่สัญญา Loan ที่ระบบ generate หรือคีย์เอง — เช่น LN-FX-001",
  "TERM (MONTHS)": "จำนวนงวดทั้งหมดของสัญญา (เป็นเดือน) — เช่น 24 = 2 ปี",
  "TERM (PERIODS)": "จำนวนงวดทั้งหมดของสัญญา",
  "PAY AT END OF MONTH": "ติ๊ก = ผ่อนชำระวันสุดท้ายของเดือน (28/30/31) · ไม่ติ๊ก = ผ่อนตามวันที่กำหนด",
  "RESIDUAL VALUE (RV)": "มูลค่าคงเหลือเมื่อจบสัญญา (ขายต่อ/ปิดสัญญา) — สำหรับ Loan ที่มี Balloon · ที่ MGC ใช้กับ HP มักเป็น 10-20% ของราคารถ",
  "INCLUDE RV IN INSTALLMENT": "ติ๊ก = รวม RV กับงวดสุดท้าย (Balloon ในงวดสุดท้าย) · ไม่ติ๊ก = แยกเป็นงวด Balloon ต่างหาก",
  "BALLOON OPTION": "ตำแหน่งของยอด Balloon: (1) พร้อมค่างวด → รวมในงวดสุดท้าย (2) หลัง Term → เพิ่มงวด N+1 (3) ก่อน Term → ลดงวดเหลือ N-1 — คุยกับธนาคารตอนทำสัญญา",
  "EFFECTIVE INTEREST RATE / YEAR (%)": "อัตราดอกเบี้ย Effective ที่แท้จริงต่อปี (% ต่อปี) — คำนวณรวมค่าธรรมเนียมต่าง ๆ",
  "EFFECTIVE INTEREST RATE %": "อัตราดอกเบี้ย Effective ที่แท้จริงต่อปี (Annual Effective Rate)",
  "IRR / MONTH (%)": "Internal Rate of Return ต่อเดือน (Monthly IRR) — ใช้ตามมาตรฐาน TFRS 9 สำหรับคำนวณ Amortized Cost",
  "IRR %": "Internal Rate of Return — อัตราผลตอบแทนที่แท้จริงตามตารางการชำระ",
  "PRINCIPLE": "ยอดเงินต้น (หมายเหตุ: NetSuite UI ใช้คำว่า \"Principle\" สำหรับ \"Principal\")",
  "ALLOW PREPAYMENT": "เปิด/ปิดสิทธิ์ลูกค้าในการชำระคืนก่อนกำหนด — Yes (Full+Partial) · Full Only (ปิดยอดอย่างเดียว) · Partial Only (ผ่อนเพิ่มอย่างเดียว) · No (ห้าม)",
  "FEE BASE": "ฐานคำนวณค่าปรับ Prepayment Fee — (1) Outstanding Principal = หนี้คงเหลือ (2) Prepayment Amount = ยอดที่ชำระคืน · อิงตาม MoM Workshop",
  "PERIOD (จากวันที่เริ่มสัญญา)": "ระยะเวลานับจากวันเริ่มสัญญา — ใช้กำหนด Tier ของค่าปรับ (ปิดเร็วโดนปรับสูง / ปิดช้าโดนปรับต่ำ)",
  "AR/AP RECEIPT#": "เลขที่ AR Receipt (HP — ลูกค้าจ่ายมา) หรือ AP Payment (Lease Other — MGC จ่ายไป) — ดึงจาก AR/AP Module แบบ real-time",
  "EXCL. LIAB": "Exclude from Lease Liability — ติ๊กถ้า payment นี้ไม่นับเป็นส่วนหนึ่งของ Lease Liability ตาม TFRS 16 (เช่น Variable Lease Payments)",
  "BASE RATE": "อัตราดอกเบี้ยอ้างอิงที่ธนาคารประกาศ (MLR / MOR / MRR / Fixed) — เปลี่ยนตามนโยบายธนาคาร",
  "MARGIN": "ส่วนต่างที่ธนาคารบวก/ลบจาก Base Rate ตามสัญญา — เช่น MLR -1.5% (ลบ 1.5%) หรือ MLR +0.5% (บวก 0.5%)",
  "EFFECTIVE RATE": "อัตราดอกเบี้ยจริงที่ใช้คำนวณ = Base Rate + Margin · ใช้แสดงใน Notes Disclosure งบการเงิน (MLR 7% − 1.5% = 5.5%)",
  "BANK STATEMENT": "ช่องทางตัดชำระแบบ Case A (HP/Loan): Import Bank Statement → Direct cut ที่ระบบ Lease · ไม่ผ่าน AP Module",
  "AP MODULE": "ช่องทางตัดชำระแบบ Case B (Lease IFRS 16): ส่งรายการไป AP Module → AP ทำจ่าย (มี WHT 3%, Approval Flow) → flag กลับ",
  "NEXT PAYMENT BATCH": "รอบเตรียมข้อมูลจ่ายค่างวด — ปกติ 10-15 วันก่อนถึงกำหนด · สัญญาที่ต้องปิดก่อนรอบจ่ายสามารถ mark ดึงออกได้",
  "NETSUITE CLEARING": "บัญชีพักเจ้าหนี้ Leasing ใน NetSuite — เมื่อ Create HP Contract จะ Dr. AP-Leasing Clearing / Cr. Lease Liability (MOM §9.4)",
  "CLOSE DATE": "วันที่ปิดบัญชีจริง — ใช้คำนวณ Outstanding และ Rebate ของดอกเบี้ย + VAT",
  "NEW TERM (MONTHS)": "จำนวนงวดของสัญญาใหม่หลัง Roll Over — ลูกค้าและธนาคารตกลงร่วมกัน",
  "NEW INTEREST RATE (%)": "อัตราดอกเบี้ยของสัญญาใหม่หลัง Roll Over — มักสูงกว่าเดิม (ลูกค้ามีประวัติจ่ายไม่ไหวต่อ Balloon)",
  "TRANSFER DATE": "วันที่โอนทรัพย์สิน (ROU → PPE / IP / Sale / OL / PPE → IP) — ใช้เป็น cut-off สำหรับค่าเสื่อมและ JE",
  "CARRYING AMOUNT": "มูลค่าตามบัญชี ณ วันที่โอน (NBV) = Gross Asset − Accumulated Depreciation",
  "COMPONENT": "องค์ประกอบของยอดที่ต้องชำระเมื่อปิดก่อนกำหนด — เงินต้น (ไม่ลด) · ดอกเบี้ยที่เหลือ (ลดได้) · VAT ที่เหลือ (ลดได้)",
  "REBATE %": "เปอร์เซ็นต์ส่วนลดที่ธนาคารให้ — ใช้กับดอกเบี้ยและ VAT · เงินต้นไม่ลด",
  "REBATE AMOUNT": "ยอดส่วนลด = Outstanding × Rebate %",
  "NET PAY": "ยอดที่ต้องจ่ายจริง = Outstanding − Rebate Amount",
  "TOTAL SETTLEMENT AMOUNT": "ยอดรวมที่ลูกค้าต้องจ่ายเพื่อปิดสัญญา = เงินต้น + ดอกเบี้ย (หลัง rebate) + VAT (หลัง rebate)",
  "ITEM": "รายการที่เปลี่ยนแปลง — ค่าเช่า / ระยะเวลา / อัตราดอกเบี้ย",
  "ORIGINAL": "ค่าเดิมก่อน Re-measurement",
  "AFTER RE-MEASURE": "ค่าใหม่หลัง Re-measurement (input โดย user)",
  "Δ CHANGE": "ส่วนต่าง = After − Original · นำไปปรับเข้า Lease Liability และ ROU Asset ทั้งสองฝั่ง (MOM §7.1)",
  "ADJUSTMENT": "JE Adjustment ที่ปรับเข้า Lease Liability + ROU Asset · Day 1 ของสัญญาใหม่ ROU อาจ ≠ Lease Liability (Carry-over)",
  "ORIGINAL CONTRACT": "สัญญาเดิมที่จะถูกปิดในการ Roll Over — ระบบเก็บ cross-reference ไว้",
  "BALLOON OUTSTANDING": "ยอด Balloon คงเหลือของสัญญาเดิม — ใช้เป็นเงินต้นตั้งต้นของสัญญาใหม่",
  "NEW PRINCIPAL": "เงินต้นของสัญญาใหม่ = Balloon Outstanding (ไม่มีเงินใหม่ไหลเข้า เป็นการต่ออายุภาระเดิม)",
  "DAYS OVERDUE": "จำนวนวันที่จ่ายช้า = วันที่ชำระจริง − Original Due Date",
  "LATE FEE RATE (%)": "อัตราค่าปรับจ่ายล่าช้า — กำหนดในสัญญา (ปกติ 0.5% ต่อเดือนของ Outstanding)",
  "LATE FEE AMOUNT": "ค่าปรับ = Outstanding × (Late Fee Rate × Days Overdue / 30) · ไม่ผูกกับ schedule · ลงระบบบัญชีแยก",
};

// Total entries: 416
